#!/usr/bin/env python3
"""PdfCraft SDK Capability Tour: a 5-page generated showcase PDF.

# Architecture Reference
Script: docs/sdk/examples/python/sdk_capability_tour.py
Purpose:
    Builds a visually rich PDF entirely through the public PdfCraft Python SDK
    (`DocumentSession`, `Style`, `StyleTransition`, `Color`, `Rect`,
    `DocTextFinderConfig`). Every number printed in the document is computed by
    the script at build time, so the PDF documents its own construction.

      Page 1  Cover: generated interference-pattern hero image, stat tiles.
      Page 2  Typography: font families, StyleTransition runs, word-wrapped
              text boxes, and a 24-colour palette heat strip.
      Page 3  Data: a vector bar chart, a raster Mandelbrot plate, and a table.
      Page 4  Review: find_text() hits drawn as highlights, stamps, comment
              cards, and form-field views.
      Page 5  Landscape roadmap: page-geometry control, a Gantt-style timeline (illustrative data).

Usage:
    python3 docs/sdk/examples/python/sdk_capability_tour.py
    python3 docs/sdk/examples/python/sdk_capability_tour.py \
        --output sample-docs/outputs/sdk_capability_tour.pdf --render-previews

Notes:
    * Built-in PDF fonts only encode Latin-1 here, so all text is plain ASCII.
    * `--render-previews` needs `pdftoppm` (poppler) on PATH.
"""

from __future__ import annotations

import argparse
import colorsys
import io
import math
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[4]
SDK_PYTHON_DIR = REPO_ROOT / "sdks" / "python"
if str(SDK_PYTHON_DIR) not in sys.path:
    sys.path.insert(0, str(SDK_PYTHON_DIR))

from PIL import Image  # noqa: E402

from pdfcraft import (  # noqa: E402
    Color,
    DocTextFinderConfig,
    DocumentSession,
    Rect,
    Style,
    StyleTransition,
    measure_text_width,
)

LETTER_W, LETTER_H = 612.0, 792.0

# ---- palette ---------------------------------------------------------------
INK = Color.rgb(0.07, 0.09, 0.16)
NIGHT = Color.rgb(0.04, 0.06, 0.13)
PAPER = Color.rgb(0.985, 0.982, 0.97)
TEAL = Color.rgb(0.05, 0.55, 0.52)
CORAL = Color.rgb(0.93, 0.36, 0.30)
GOLD = Color.rgb(0.96, 0.72, 0.20)
VIOLET = Color.rgb(0.42, 0.31, 0.78)
MUTED = Color.rgb(0.42, 0.45, 0.52)
RULE = Color.rgb(0.84, 0.85, 0.88)
WHITE = Color.white()


def S(font: str, size: float, color: Color = INK) -> Style:
    return Style(font_name=font, font_size=size, color=color)


def hsv(h: float, s: float = 0.65, v: float = 0.92) -> Color:
    r, g, b = colorsys.hsv_to_rgb(h % 1.0, s, v)
    return Color.rgb(r, g, b)


def full_bleed(doc: DocumentSession, page: int, color: Color, w: float = LETTER_W, h: float = LETTER_H) -> None:
    """Covers the SDK's default page frame with a solid background."""
    doc.add_rect(page, Rect(0, 0, w, h), fill_color=color)


def heading(doc: DocumentSession, page: int, kicker: str, title: str, dark: bool = False) -> None:
    fg = WHITE if dark else INK
    doc.add_rect(page, Rect(48, 716, 36, 5), fill_color=CORAL)
    doc.add_text(page, kicker.upper(), 48, 730, S("Helvetica-Bold", 9, GOLD if dark else CORAL))
    doc.add_text(page, title, 48, 684, S("Helvetica-Bold", 30, fg))


def footer(doc: DocumentSession, page: int, w: float = LETTER_W, dark: bool = False) -> None:
    c = Color.rgb(0.6, 0.65, 0.75) if dark else MUTED
    doc.add_rect(page, Rect(48, 46, w - 96, 0.8), fill_color=c)
    doc.add_text(page, "PdfCraft Python SDK  |  generated by sdk_capability_tour.py", 48, 30, S("Helvetica", 8, c))
    doc.add_text(page, f"{page:02d}", w - 64, 30, S("Helvetica-Bold", 9, c))


# ---- generated imagery (PIL only, no external assets) ----------------------
def interference_hero(width: int = 516, height: int = 300) -> bytes:
    """Moire-style interference of three radial wave sources, mapped to a duotone ramp."""
    img = Image.new("RGB", (width, height))
    px = img.load()
    sources = [(0.22 * width, 0.30 * height), (0.78 * width, 0.62 * height), (0.50 * width, 1.05 * height)]
    for y in range(height):
        for x in range(width):
            v = sum(math.sin(math.hypot(x - sx, y - sy) * 0.095) for sx, sy in sources) / 3.0
            t = (v + 1.0) / 2.0
            hue = 0.52 + 0.30 * t  # teal -> violet -> magenta
            r, g, b = colorsys.hsv_to_rgb(hue, 0.75, 0.25 + 0.75 * t**1.6)
            px[x, y] = (int(r * 255), int(g * 255), int(b * 255))
    buf = io.BytesIO()
    img.save(buf, format="PNG")
    return buf.getvalue()


def mandelbrot(width: int = 300, height: int = 200, max_iter: int = 70) -> bytes:
    img = Image.new("RGB", (width, height))
    px = img.load()
    for j in range(height):
        for i in range(width):
            c = complex(-2.2 + 3.1 * i / width, -1.0 + 2.0 * j / height)
            z, n = 0j, 0
            while abs(z) <= 2.0 and n < max_iter:
                z = z * z + c
                n += 1
            if n == max_iter:
                px[i, j] = (6, 8, 20)
            else:
                r, g, b = colorsys.hsv_to_rgb(0.62 - 0.55 * (n / max_iter) ** 0.5, 0.8, 1.0)
                px[i, j] = (int(r * 255), int(g * 255), int(b * 255))
    buf = io.BytesIO()
    img.save(buf, format="PNG")
    return buf.getvalue()


# ---- pages -----------------------------------------------------------------
def page_cover(doc: DocumentSession, stats: dict) -> None:
    p = doc.add_page(LETTER_W, LETTER_H).page_number
    full_bleed(doc, p, NIGHT)
    doc.add_rect(p, Rect(0, 0, 14, LETTER_H), fill_color=TEAL)

    doc.add_text(p, "PDFCRAFT  /  PYTHON SDK", 48, 736, S("Helvetica-Bold", 10, GOLD))
    doc.add_text(p, "Build documents", 48, 668, S("Helvetica-Bold", 44, WHITE))
    doc.add_text(p, "like software.", 48, 618, S("Helvetica-Bold", 44, hsv(0.50, 0.55, 1.0)))
    doc.add_text(p, "Pages, type, vectors, imagery and review markup,", 48, 586, S("Helvetica", 13, Color.rgb(0.75, 0.8, 0.9)))
    doc.add_text(p, "all composed from a few lines of Python.", 48, 569, S("Helvetica", 13, Color.rgb(0.75, 0.8, 0.9)))

    # Hero image sits above a thin accent frame (frame is a shape: drawn beneath the image).
    doc.add_rect(p, Rect(46, 226, 520, 304), fill_color=GOLD)
    doc.add_image(p, interference_hero(), Rect(48, 228, 516, 300), image_id="Hero")

    # Stat tiles (values are computed live from the build).
    tiles = [
        (str(stats["pages"]), "pages", TEAL),
        (f"{stats['text_runs']}", "text runs", CORAL),
        (f"{stats['shapes']}", "vector shapes", VIOLET),
        (f"{stats['images']}", "raster images", GOLD),
    ]
    x = 48.0
    for value, label, color in tiles:
        doc.add_rect(p, Rect(x, 120, 120, 78), fill_color=Color.rgb(0.09, 0.12, 0.22), stroke_color=color, line_width=1.5)
        doc.add_rect(p, Rect(x, 192, 120, 6), fill_color=color)
        doc.add_text(p, value, x + 14, 148, S("Helvetica-Bold", 28, WHITE))
        doc.add_text(p, label, x + 14, 130, S("Helvetica", 9.5, Color.rgb(0.7, 0.76, 0.88)))
        x += 132.0

    doc.add_text(p, "Counts above are measured from the live DocumentSession before saving.", 48, 92, S("Helvetica", 8.5, Color.rgb(0.55, 0.6, 0.72)))
    footer(doc, p, dark=True)


def page_typography(doc: DocumentSession) -> None:
    p = doc.add_page(LETTER_W, LETTER_H).page_number
    full_bleed(doc, p, PAPER)
    heading(doc, p, "02  /  Typography", "Type & Style")

    # Font family specimen
    families = [("Helvetica", "Helvetica"), ("Times-Roman", "Times-Roman"), ("Courier", "Courier"),
                ("Helvetica-Bold", "Helvetica-Bold"), ("Times-Bold", "Times-Bold"), ("Courier-Bold", "Courier-Bold")]
    y = 640.0
    for i, (label, font) in enumerate(families):
        col, row = i % 3, i // 3
        x = 48 + col * 176
        yy = y - row * 70
        doc.add_rect(p, Rect(x, yy - 44, 164, 60), fill_color=WHITE, stroke_color=RULE, line_width=0.8)
        doc.add_text(p, "Aa Gg 42", x + 12, yy - 14, S(font, 24, INK))
        doc.add_text(p, label, x + 12, yy - 36, S("Helvetica", 8, MUTED))

    # StyleTransition: mixed styles inside a single logical line
    doc.add_text(p, "StyleTransition: one line, many voices", 48, 484, S("Helvetica-Bold", 12, TEAL))
    line = "Render  fast.  Edit  safely.  Ship  everywhere."
    doc.add_styled_line(
        p, 48, 452, line,
        [
            StyleTransition(0, S("Helvetica-Bold", 22, CORAL)),
            StyleTransition(8, S("Times-Roman", 22, INK)),
            StyleTransition(14, S("Helvetica-Bold", 22, VIOLET)),
            StyleTransition(21, S("Courier", 22, INK)),
            StyleTransition(27, S("Helvetica-Bold", 22, TEAL)),
            StyleTransition(36, S("Times-Roman", 22, INK)),
        ],
    )

    # Word-wrapped text boxes in two columns
    body = (
        "PdfCraft keeps the PDF object graph as the single source of truth. The Python "
        "SDK wraps that engine in a small, typed surface: sessions own pages, pages own "
        "content, and every operation either succeeds or raises a precise, catchable error. "
        "Text boxes wrap to their rectangle automatically, so layout code stays declarative."
    )
    col_w = 252.0
    for i, (title, color) in enumerate([("Declarative layout", TEAL), ("Predictable output", CORAL)]):
        x = 48 + i * (col_w + 12)
        doc.add_rect(p, Rect(x, 262, col_w, 170), fill_color=WHITE, stroke_color=RULE, line_width=0.8)
        doc.add_rect(p, Rect(x, 426, col_w, 6), fill_color=color)
        doc.add_text(p, title, x + 12, 404, S("Helvetica-Bold", 13, color))
        doc.add_text_box(p, body, Rect(x + 6, 266, col_w - 12, 130), S("Times-Roman", 10.5, INK), padding=6, line_spacing=1.35)

    # Colour palette heat strip: 24 hues x 3 tones, plain rectangles
    doc.add_text(p, "Generated palette: 24 hues x 3 tones", 48, 232, S("Helvetica-Bold", 12, TEAL))
    cell, gap = 19.5, 2.0
    for r_i, (sat, val) in enumerate([(0.85, 0.95), (0.60, 0.98), (0.35, 1.0)]):
        for c_i in range(24):
            doc.add_rect(p, Rect(48 + c_i * (cell + gap), 168 - r_i * (cell + gap) + 40, cell, cell), fill_color=hsv(c_i / 24, sat, val))
    doc.add_text(p, "Colors are plain Color.rgb values; the heat strip is 72 add_rect() calls in a double loop.",
                 48, 100, S("Helvetica", 9, MUTED))
    footer(doc, p)


def page_data(doc: DocumentSession) -> None:
    p = doc.add_page(LETTER_W, LETTER_H).page_number
    full_bleed(doc, p, PAPER)
    heading(doc, p, "03  /  Data & Imagery", "Charts & Plates")

    # Vector bar chart (sine-modulated series, computed)
    cx, cy, cw, ch = 48.0, 450.0, 516.0, 190.0
    doc.add_rect(p, Rect(cx, cy, cw, ch), fill_color=WHITE, stroke_color=RULE, line_width=0.8)
    for g in range(1, 5):  # gridlines as hairline rects
        doc.add_rect(p, Rect(cx + 10, cy + 14 + g * 36, cw - 20, 0.5), fill_color=RULE)
    series = [58 + 38 * math.sin(i / 2.3) + 2.5 * i for i in range(16)]
    bar_w, gap = 22.0, 9.0
    peak = max(series)
    for i, v in enumerate(series):
        h = v / peak * 150.0
        x = cx + 18 + i * (bar_w + gap)
        color = hsv(0.50 + 0.28 * i / (len(series) - 1), 0.72, 0.88)
        doc.add_rect(p, Rect(x, cy + 14, bar_w, h), fill_color=color)
        doc.add_text(p, f"{v:.0f}", x + 3, cy + 18 + h, S("Helvetica", 7, MUTED))
    doc.add_text(p, "Throughput by build (MB/s, synthetic series)", cx, cy + ch + 10, S("Helvetica-Bold", 11, INK))

    # Raster plate: mandelbrot, with a caption below (images draw above text, so no overlap)
    doc.add_rect(p, Rect(46, 196, 304, 204), fill_color=INK)
    doc.add_image(p, mandelbrot(), Rect(48, 198, 300, 200), image_id="Mandelbrot")
    doc.add_text(p, "Plate I: Mandelbrot set", 48, 180, S("Helvetica-Bold", 10, INK))
    doc.add_text(p, "rendered in pure Python, embedded via add_image()", 48, 167, S("Helvetica", 8.5, MUTED))

    # Table
    tx, ty = 366.0, 196.0
    rows = [("Operation", "Cost"), ("add_page", "O(1)"), ("add_text", "O(1)"), ("add_image", "O(px)"),
            ("find_text", "O(n)"), ("save", "O(n)"), ("render_page", "O(px)")]
    row_h = 29.0
    for r_i, (a, b) in enumerate(rows):
        yy = ty + (len(rows) - 1 - r_i) * row_h
        if r_i == 0:
            doc.add_rect(p, Rect(tx, yy, 198, row_h), fill_color=INK)
        else:
            doc.add_rect(p, Rect(tx, yy, 198, row_h), fill_color=WHITE if r_i % 2 else Color.rgb(0.94, 0.96, 0.97), stroke_color=RULE, line_width=0.5)
        font = "Helvetica-Bold" if r_i == 0 else "Courier"
        doc.add_text(p, a, tx + 10, yy + 10, S(font, 9.5, WHITE if r_i == 0 else INK))
        doc.add_text(p, b, tx + 120, yy + 10, S("Helvetica-Bold" if r_i == 0 else "Helvetica", 9.5, WHITE if r_i == 0 else TEAL))
    footer(doc, p)


def page_review(doc: DocumentSession) -> dict:
    p = doc.add_page(LETTER_W, LETTER_H).page_number
    full_bleed(doc, p, PAPER)
    heading(doc, p, "04  /  Review & Forms", "Find, Mark, Approve")

    # Log lines; find_text() locates level keywords, then we paint highlights beneath them.
    log = [
        ("INFO  engine boot, 0 plugins", ),
        ("WARN  font fallback for U+2603", ),
        ("INFO  page 3 rendered in 11 ms", ),
        ("ERROR xref entry 42 repaired", ),
        ("INFO  incremental save complete", ),
        ("WARN  image downsampled to 150 dpi", ),
        ("ERROR signature digest mismatch", ),
    ]
    panel = Rect(48, 468, 330, 190)
    doc.add_rect(p, panel, fill_color=Color.rgb(0.07, 0.09, 0.15))
    mono = S("Courier", 10, Color.rgb(0.8, 0.86, 0.95))
    for i, (txt,) in enumerate(log):
        doc.add_text(p, txt, panel.x + 12, panel.y + panel.height - 24 - i * 22, mono)

    hits = []
    for query, color in [("ERROR", CORAL), ("WARN", GOLD)]:
        cfg = DocTextFinderConfig(case_sensitive=True, regex=True)
        for m in doc.find_text(rf"^{query}", cfg):
            if m.page_number != p:
                continue
            hits.append((query, m))
            b = m.bounding_box
            w = measure_text_width(query, mono)  # exact for Courier
            doc.add_rect(p, Rect(b.x - 2, b.y - 3, w + 4, 14), fill_color=color)
    # re-draw keyword text on top of highlight (text layer is above shapes already)

    doc.add_text(p, "find_text() results", 400, 636, S("Helvetica-Bold", 12, TEAL))
    n_err = sum(1 for q, _ in hits if q == "ERROR")
    n_warn = sum(1 for q, _ in hits if q == "WARN")
    for i, (label, val, color) in enumerate([("ERROR", n_err, CORAL), ("WARN", n_warn, GOLD)]):
        yy = 570 - i * 62
        doc.add_rect(p, Rect(400, yy, 164, 52), fill_color=WHITE, stroke_color=color, line_width=1.5)
        doc.add_text(p, str(val), 414, yy + 14, S("Helvetica-Bold", 26, color))
        doc.add_text(p, f"{label} hits found", 450, yy + 20, S("Helvetica", 9.5, INK))

    # Stamps
    doc.add_stamp(p, "APPROVED", Rect(48, 372, 150, 52), color=Color.rgb(0.10, 0.60, 0.35))
    doc.add_stamp(p, "REVIEWED", Rect(212, 372, 150, 52), color=Color.rgb(0.20, 0.40, 0.80))
    doc.add_stamp(p, "CONFIDENTIAL", Rect(376, 372, 188, 52), color=CORAL)

    # Comment cards
    doc.add_comment_card(p, "R. Chen - Reviewer", "The xref repair is logged but not surfaced to the user. Can we show a banner?",
                         Rect(48, 252, 250, 96))
    doc.add_comment_card(p, "A. Okafor - Author", "Agreed. Added to the sample timeline on page 5; the SDK already exposes the repair record.",
                         Rect(314, 252, 250, 96))

    # Form field views
    doc.add_form_field_view(p, "Reviewer", Rect(48, 176, 230, 26), value="Rin Chen")
    doc.add_form_field_view(p, "Date", Rect(294, 176, 120, 26), value="2026-10-10")
    doc.add_form_field_view(p, "Release approved", Rect(430, 176, 22, 22), value="true", field_type="checkbox")
    doc.add_form_field_view(p, "Needs legal review", Rect(430, 120, 22, 22), value="", field_type="checkbox")
    doc.add_form_field_view(p, "Notes", Rect(48, 110, 366, 26), value="Ship after signature check is fixed.")
    footer(doc, p)
    return {"err": n_err, "warn": n_warn}


def page_roadmap(doc: DocumentSession) -> None:
    w, h = LETTER_H, LETTER_W  # landscape: 792 x 612
    p = doc.add_page(w, h).page_number
    full_bleed(doc, p, NIGHT, w, h)
    doc.add_rect(p, Rect(48, h - 76, 36, 5), fill_color=CORAL)
    doc.add_text(p, "05  /  PAGE GEOMETRY", 48, h - 62, S("Helvetica-Bold", 9, GOLD))
    doc.add_text(p, "Landscape Timeline", 48, h - 106, S("Helvetica-Bold", 30, WHITE))

    quarters = ["Q1", "Q2", "Q3", "Q4"]
    gx, gw = 220.0, 520.0
    qw = gw / 4
    for i, q in enumerate(quarters):
        doc.add_rect(p, Rect(gx + i * qw, 150, qw - 2, 300), fill_color=Color.rgb(0.08, 0.11, 0.2))
        doc.add_text(p, q, gx + i * qw + 10, 428, S("Helvetica-Bold", 12, Color.rgb(0.7, 0.76, 0.9)))
    tracks = [
        ("Workstream A", 0.0, 2.2, TEAL),
        ("Workstream B", 0.8, 3.0, CORAL),
        ("Workstream C", 1.6, 3.6, VIOLET),
        ("Workstream D", 0.3, 1.6, GOLD),
        ("Workstream E", 2.2, 4.0, hsv(0.58, 0.6, 0.95)),
    ]
    for i, (name, start, end, color) in enumerate(tracks):
        yy = 380 - i * 54
        doc.add_text(p, name, 48, yy + 10, S("Helvetica", 11, Color.rgb(0.85, 0.89, 0.96)))
        doc.add_rect(p, Rect(gx + start * qw, yy, (end - start) * qw - 2, 30), fill_color=color)
        doc.add_text(p, f"{end - start:.1f} qtrs", gx + start * qw + 10, yy + 10, S("Helvetica-Bold", 10, NIGHT))
    doc.add_stamp(p, "DRAFT", Rect(w - 190, 60, 142, 44), color=GOLD)
    footer(doc, p, w, dark=True)


# ---- driver ----------------------------------------------------------------
def build(output: Path, render_previews: bool) -> Path:
    doc = DocumentSession.create()
    # The cover reports real counts, so measure a throwaway dry run first.
    dry = DocumentSession.create()
    _populate(dry, {"pages": 5, "text_runs": 0, "shapes": 0, "images": 0})
    stats = {
        "pages": dry.num_pages,
        "text_runs": sum(len(v) for v in dry._text_elements.values()),
        "shapes": sum(len(v) for v in dry._shape_elements.values()),
        "images": sum(len(v) for v in dry._image_elements.values()),
    }
    _populate(doc, stats)
    result = doc.save(output)
    print(f"Saved {result.path} ({result.size_bytes / 1024:.1f} KiB, {doc.num_pages} pages)")
    if render_previews:
        prev_dir = output.parent / "previews"
        for n in range(1, doc.num_pages + 1):
            png = doc.render_page(n, prev_dir / f"{output.stem}_page_{n}.png", dpi=110)
            print(f"  preview: {png}")
    return output


def _populate(doc: DocumentSession, stats: dict) -> None:
    page_cover(doc, stats)
    page_typography(doc)
    page_data(doc)
    page_review(doc)
    page_roadmap(doc)


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--output", type=Path, default=REPO_ROOT / "sample-docs" / "outputs" / "sdk_capability_tour.pdf")
    ap.add_argument("--render-previews", action="store_true", help="also render PNG previews via pdftoppm")
    args = ap.parse_args()
    build(args.output, args.render_previews)


if __name__ == "__main__":
    main()
