"""PdfCraft Python SDK (Issue #872).

# Architecture Reference
Module: sdks/python/pdfcraft/__init__.py
Purpose:
    Public package exports for the unified PdfCraft Python client,
    conforming to Datalogics APDFL 21 domain taxonomy.
"""

from pdfcraft.errors import (
    ConflictError,
    InvalidArgumentError,
    NotFoundError,
    PdfCraftError,
    ProblemDetails,
    QuotaExceededError,
)
from pdfcraft.local import LocalClient
from pdfcraft.rest import RestClient
from pdfcraft.session import DocumentSession, measure_text_width, wrap_text_to_width
from pdfcraft.types import (
    Action,
    AcroFormExportType,
    Annotation,
    BlendMode,
    Bookmark,
    ButtonField,
    Color,
    ColorSpace,
    DocTextFinderConfig,
    DocTextFinderMatch,
    Document,
    DocumentResult,
    DocumentSource,
    Field,
    FitMode,
    GoToAction,
    HighlightAnnotation,
    ImageFormat,
    Matrix,
    MergeOptions,
    OptimizationParams,
    PDFOptimizer,
    Page,
    PermissionsFlags,
    Point,
    Quad,
    Rect,
    Redaction,
    RenderOptions,
    SignDoc,
    SplitMode,
    SplitModeType,
    SplitResult,
    Style,
    StyleTransition,
    TextField,
    URIAction,
    ViewDestination,
    Word,
    WordFinderConfig,
)

__all__ = [
    "Action",
    "AcroFormExportType",
    "Annotation",
    "BlendMode",
    "Bookmark",
    "ButtonField",
    "Color",
    "ColorSpace",
    "ConflictError",
    "DocTextFinderConfig",
    "DocTextFinderMatch",
    "Document",
    "DocumentResult",
    "DocumentSession",
    "DocumentSource",
    "Field",
    "FitMode",
    "GoToAction",
    "HighlightAnnotation",
    "ImageFormat",
    "InvalidArgumentError",
    "LocalClient",
    "Matrix",
    "measure_text_width",
    "MergeOptions",
    "NotFoundError",
    "OptimizationParams",
    "PDFOptimizer",
    "Page",
    "PdfCraftError",
    "PermissionsFlags",
    "Point",
    "ProblemDetails",
    "Quad",
    "QuotaExceededError",
    "Rect",
    "Redaction",
    "RenderOptions",
    "RestClient",
    "SignDoc",
    "SplitMode",
    "SplitModeType",
    "SplitResult",
    "Style",
    "StyleTransition",
    "TextField",
    "URIAction",
    "ViewDestination",
    "Word",
    "WordFinderConfig",
    "wrap_text_to_width",
]
